apiVersion: apps/v1
kind: Deployment
metadata:
    name: counter-project
    namespace: staging # too add the file to a ns
spec:
    selector:
        matchLabels:
            app: counter-project
            type: front-end
    replicas: 5
    template:
        metadata:
            name: counter-project
            labels:
                app: counter-project
                type: front-end
        spec:
            containers:
                - name: counter-project
                  image: 982534392122.dkr.ecr.eu-west-2.amazonaws.com/counter-project:39068a90328e5993c8f923c2ba095e809ee6ecdc
                  ports:
                    - containerPort: 3000
                  volumeMounts:
                    - name: secret-volume
                      mountPath: "/etc/secret"
                      readOnly: true
            volumes:
                - name: secret-volume
                  secret:
                    secretName: ecr-secret
            


                      

                     
