apiVersion: apps/v1
kind: Deployment
metadata:
    name: core-serve-frontend
    namespace: staging # too add the file to a ns
spec:
    selector:
        matchLabels:
            app: core-serve-frontend
            type: front-end
    replicas: 3
    template:
        metadata:
            name: core-serve-frontend
            labels:
                app: core-serve-frontend
                type: front-end
        spec:
            containers:
                - name: core-serve-frontend
                  image: 911167885172.dkr.ecr.eu-west-2.amazonaws.com/core-serve-frontend-app:PR-81-1
                  ports:
                    - containerPort: 3000
            imagePullSecrets:
                - name: ecr-secret
            #       volumeMounts:
            #         - name: secret-volume
            #           mountPath: "/etc/secret"
            #           readOnly: true
            # volumes:
            #     - name: secret-volume
            #       secret:
            #         secretName: ecr-secret
            


                      

                     
