apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ecr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAmFa5nYq5//aYmoE/AqVVo0FanbVenRMiitWl5LwNzVdm/s+BOUjaSbGLmKTg3Twc0N73tqclg6+OqZOhZxnklHMW8FEDQxROv7hBW7pSCTaI/HgiTHTyoONdiS3i5CQEC2XJclf/IPj>
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ecr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson




