apiVersion: v1
kind: Service
metadata:
    name: counter-service
    namespace: counter
spec:
    type: NodePort
    # links the service to the pods
    # the pods was created with a label
    selector:
         app: counter-project
         type: front-end
    ports:
        - protocol: TCP
          # port on service
          port: 3000
          # port on the pod
          targetPort: 3000
          # port on the node
          nodePort: 30004
